// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GlowsBattlegrounds.Migrations
{
    [DbContext(typeof(StatsContext))]
    [Migration("20231019003358_FixDataTypesForStats")]
    partial class FixDataTypesForStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GlowsBattlegrounds.Models.GlobalStats", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("highestKills")
                        .HasColumnType("int");

                    b.Property<string>("highestKillsSteamId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("highestKillstreak")
                        .HasColumnType("int");

                    b.Property<string>("killRecordBlob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("mapDataBlob")
                        .HasColumnType("int");

                    b.Property<int>("totalDeaths")
                        .HasColumnType("int");

                    b.Property<int>("totalKills")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("GlobalStats");
                });

            modelBuilder.Entity("GlowsBattlegrounds.Models.PlayerStats", b =>
                {
                    b.Property<string>("steamId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("averageDpm")
                        .HasColumnType("float");

                    b.Property<double>("averageKd")
                        .HasColumnType("float");

                    b.Property<double>("averageKpm")
                        .HasColumnType("float");

                    b.Property<string>("firstSeen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gamertag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("highestDeathStreak")
                        .HasColumnType("int");

                    b.Property<int>("highestKillStreak")
                        .HasColumnType("int");

                    b.Property<string>("lastSeen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mapBlob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("mostDeaths")
                        .HasColumnType("int");

                    b.Property<int>("mostKills")
                        .HasColumnType("int");

                    b.Property<int>("timesBetrayed")
                        .HasColumnType("int");

                    b.Property<int>("totalDeaths")
                        .HasColumnType("int");

                    b.Property<int>("totalGames")
                        .HasColumnType("int");

                    b.Property<int>("totalKills")
                        .HasColumnType("int");

                    b.Property<int>("totalTeamkills")
                        .HasColumnType("int");

                    b.Property<string>("weaponDeathsBlob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("weaponKillsBlob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("steamId");

                    b.ToTable("PlayerStats");
                });
#pragma warning restore 612, 618
        }
    }
}
